---
- name: Have packages
  become: true
  apt:
      name:
          - clangd
          - maven

- name: No gradle from apt
  become: true
  apt:
      name:
          - gradle
      state: absent

- name: Recent gradle
  unarchive:
      remote_src: yes
      src: "{{ gradle_url }}"
      dest: /opt
      creates: "{{ gradle_path }}"

- name: Symlink gradle dir
  become: true
  file:
      src: "{{ gradle_path }}"
      dest: /opt/gradle
      state: link

- name: Symlink gradle
  become: true
  file:
      src: /opt/gradle/bin/gradle
      dest: /usr/bin/gradle
      state: link


- name: CoC extensions dir
  become: true
  file:
      path: "{{ coc_extensions_dir }}"
      state: directory

- name: CoC configuration file
  file:
      dest: "{{ ansible_user_dir }}/.config/nvim/coc-settings.json"
      src: "{{ local_repositories_dir }}/dotfiles/coc-settings.json"
      state: link

- name: CoC package.json
  copy:
      src: package.json
      dest: "{{ coc_extensions_dir }}"

- name: CoC extensions
  command:
      chdir: "{{ coc_extensions_dir }}"
      cmd: "npm install"
      creates: "{{ coc_extensions_dir }}/packages"
