---
- name: Have apt keys from NodeSource
  become: true
  apt_key:
      url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: Have NodeSource apt repository
  become: true
  apt_repository:
      repo: "deb [arch=amd64] https://deb.nodesource.com/node_{{ node_version }}.x {{ ansible_distribution_release }} main"

- name: Have packages
  become: true
  apt:
      name:
          - nodejs
          - clangd
          - maven
          - gradle

- name: CoC extensions dir
  file:
      path: "{{ coc_extensions_dir }}"
      state: directory

- name: CoC package.json
  copy:
      src: package.json
      dest: "{{ coc_extensions_dir }}"

- name: CoC extensions
  command:
      chdir: "{{ coc_extensions_dir }}"
      cmd: "npm install"
      creates: "{{ coc_extensions_dir }}/packages"
