---
- name: Have packages
  become: true
  apt:
      name:
          - clangd
          - maven
          - gradle

- name: CoC extensions dir
  file:
      path: "{{ coc_extensions_dir }}"
      state: directory


- name: CoC configuration file
  file:
      dest: "{{ ansible_user_dir }}/.config/nvim/coc-settings.json"
      src: "{{ local_repositories_dir }}/dotfiles/coc-settings.json"
      state: link

- name: CoC package.json
  copy:
      src: package.json
      dest: "{{ coc_extensions_dir }}"

- name: CoC extensions
  command:
      chdir: "{{ coc_extensions_dir }}"
      cmd: "npm install"
      creates: "{{ coc_extensions_dir }}/packages"
