---
- name: Vim Pathogen
  git:
      repo: https://github.com/tpope/vim-pathogen.git
      dest: "{{local_repositories_dir}}/vim-pathogen"

- name: Link Pathogen
  file:
      src: "{{local_repositories_dir}}/vim-pathogen/autoload/pathogen.vim"
      dest: "{{ansible_user_dir}}/.vim/autoload/pathogen.vim"
      state: link
  
- name: Vim TMUX Navigator
  git: repo=https://github.com/christoomey/vim-tmux-navigator.git dest="{{local_repositories_dir}}/vim-tmux-navigator"

- name: UltiSnips
  git: repo=https://github.com/SirVer/ultisnips.git dest="{{local_repositories_dir}}/ultisnips"

- name: Snippets
  git: repo=git://github.com/honza/vim-snippets.git dest="{{local_repositories_dir}}/vim-snippets"

- name: Fugitive
  git: repo=https://github.com/tpope/vim-fugitive.git dest="{{local_repositories_dir}}/vim-fugitive"

- name: PyFlakes
  git: repo=https://github.com/kevinw/pyflakes-vim.git dest="{{local_repositories_dir}}/pyflakes-vim"

- name: Syntastic
  git: repo=https://github.com/scrooloose/syntastic.git dest="{{local_repositories_dir}}/syntastic"

- name: Airline
  git: repo=https://github.com/bling/vim-airline.git dest="{{local_repositories_dir}}/vim-airline"

- name: CTRLP
  git: repo=https://github.com/kien/ctrlp.vim.git dest="{{local_repositories_dir}}/ctrlp.vim"

- name: supertab
  git: repo=https://github.com/ervandew/supertab.git dest="{{local_repositories_dir}}/supertab"

- name: svnj
  git: repo=https://github.com/juneedahamed/svnj.vim.git dest="{{local_repositories_dir}}/svnj.vim"

- name: Man
  git: repo=https://github.com/bruno-/vim-man.git dest="{{local_repositories_dir}}/vim-man"

- name: NerdTree
  git: repo=https://github.com/scrooloose/nerdtree dest="{{local_repositories_dir}}/nerdtree"

- name: PyDoc
  git: repo=https://github.com/fs111/pydoc.vim.git dest="{{local_repositories_dir}}/pydoc.vim"

- name: Vim-Go
  git: repo=https://github.com/fatih/vim-go.git dest="{{local_repositories_dir}}/vim-go"
      
- name: Tagbar
  git: repo=https://github.com/majutsushi/tagbar.git dest="{{local_repositories_dir}}/tagbar"
      
  #- git: repo=https://github.com/Valloric/YouCompleteMe.git dest="{{local_repositories_dir}}/YouCompleteMe" track_submodules=yes force=yes
  #  notify: Build YouCompleteMe

- file: src="{{local_repositories_dir}}/{{item}}" dest="{{ansible_user_dir}}/.vim/bundle/{{item}}" state=link
  with_items:
      - ultisnips
      - vim-snippets
      - vim-fugitive
      - pyflakes-vim
      - syntastic
      - vim-airline
      - ctrlp.vim
      - supertab
      - svnj.vim
      - vim-man
      - nerdtree
      - pydoc.vim
      - vim-go
      - tagbar
        #- YouCompleteMe
