---
- name: Add PPA for NeoVim
  become: true
  apt_repository:
      repo: ppa:neovim-ppa/stable

- name: Install NeoVim
  become: true
  apt:
      name: neovim

- name: Install NeoVim pip package for Python 2
  become: true
  pip:
      name: neovim
      executable: pip2

- name: Install NeoVim pip package for Python 3
  become: true
  pip:
      name: neovim
      executable: pip3

- name: Have a configuration directory for NeoVim
  file:
      dest: "{{ansible_user_dir}}/.config/nvim"
      state: directory
      mode: 0750

- name: Have my NeoVim configuration files
  file:
      dest: "{{ansible_user_dir}}/.config/nvim/init.vim"
      src: "{{local_repositories_dir}}/dotfiles/init.vim"
      state: link
