---
- name: Have apt keys from NodeSource
  become: true
  apt_key:
      url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: Have NodeSource apt repository
  become: true
  apt_repository:
      repo: "deb [arch=amd64] https://deb.nodesource.com/node_{{ node_version }}.x {{ ansible_distribution_release }} main"

- name: Add PPA for NeoVim
  become: true
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int < 20
  apt_repository:
      repo: ppa:neovim-ppa/stable

- name: Install NeoVim
  become: true
  apt:
      name:
          - neovim
          - nodejs
          - ranger

- name: Have ranger config directory
  file:
      path: "{{ ansible_user_dir }}/.config/ranger/plugins"
      state: directory

- name: Have devicons for ranger
  git:
      repo: https://github.com/alexanderjeurissen/ranger_devicons
      dest: "{{ ansible_user_dir }}/.config/ranger/plugins/ranger_devicons"

- name: Configure ranger
  blockinfile:
      dest: "{{ ansible_user_dir }}/.config/ranger/rc.conf"
      create: yes
      block: |
          set preview_images true
          set preview_images_method ueberzug
          default_linemode devicons
          set show_hidden true

- name: Install pip3
  become: true
  apt:
      name: python3-pip

- name: Install setuptools
  become: true
  apt:
      name: python-setuptools

- name: Install NeoVim pip package for Python 3
  become: true
  pip:
      executable: pip3
      name:
          - neovim

- name: Have ueberzug
  when: desktop.stat.exists
  pip:
      executable: pip3
      name:
          - ueberzug

- name: Install NeoVim pip package for Python 2
  become: true
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int < 18
  pip:
      name: neovim
      executable: pip2

- name: Have a configuration directory for NeoVim
  file:
      dest: "{{ ansible_user_dir }}/.config/nvim"
      state: directory
      mode: 0750

- name: Have my NeoVim configuration files
  file:
      dest: "{{ ansible_user_dir }}/.config/nvim/init.vim"
      src: "{{ local_repositories_dir }}/dotfiles/init.vim"
      state: link
