---
- name: Check if this is a desktop environment
  stat:
      path: /usr/bin/broadwayd
  register: desktop

- name: Have my dotfiles
  git: 
      update: no
      repo: https://github.com/RobertLarsen/dotfiles.git
      dest: "{{ local_repositories_dir }}/dotfiles"

- name: Install neovim
  when: ansible_distribution == "Ubuntu"
  include_tasks: install_neovim.yml

- name: Install language server
  import_tasks: conquer_of_completion.yml

- name: Install vim and dependencies, Debian version
  when: ansible_os_family == "Debian"
  become: true
  apt:
      update_cache: yes
      name:
      - neovim
      - git
      - clang
      - build-essential
      - cmake
      - python3-dev
      - golang-go
      - tmux
      - shellcheck
      - universal-ctags

- name: Install python-dev on Debian lower than 20
  when: ansible_os_family == "Debian"
  become: true
  apt:
      name:
          python-dev

- name: Install vim and dependencies, RedHat version
  when: ansible_os_family == "RedHat"
  become: true
  yum:
      name:
      - vim-enhanced
      - git
      - clang
      - gcc
      - gcc-c++
      - cmake
      - python-devel
      - ctags
      - golang-bin
      - golang-docs
      - tmux
      - shellcheck

- name: Symlink pip to pip3
  become: true
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 20
  file:
      dest: /usr/bin/pip
      src: /usr/bin/pip3
      state: link

# I had .vimrc and .tmux.conf copied to the $HOME folder
# Now I would rather have symlinks to a GitHub repo
# So if they are files, delete them
- name: Check if .vimrc is a file
  stat: path="{{ ansible_user_dir }}/.vimrc"
  register: vimrc

- name: Check if .tmux.conf is a file
  stat: path="{{ ansible_user_dir }}/.tmux.conf"
  register: tmux_conf

- name: Delete .vimrc if it is a file
  file: path="{{ ansible_user_dir }}/.vimrc" state=absent
  when: vimrc.stat.isreg is defined and vimrc.stat.isreg

- name: Delete .tmux.conf if it is a file
  file: path="{{ ansible_user_dir }}/.tmux.conf" state=absent
  when: tmux_conf.stat.isreg is defined and tmux_conf.stat.isreg

- name: Know package versions
  package_facts:
      manager: auto

- name: Install generic TMUX configuration file
  file:
      dest: "{{ ansible_user_dir }}/.tmux.conf"
      src: "{{ local_repositories_dir }}/dotfiles/tmux.conf"
      state: link

- name: Install version specific TMUX configuration file
  file:
      dest: "{{ ansible_user_dir }}/.tmuxX.conf"
      src: "{{ local_repositories_dir }}/dotfiles/tmux{{ ansible_facts.packages['tmux'][0].version[0] }}.conf"
      state: link

- name: Install PHP Coding Standard Fixer
  become: true
  get_url:
      url: http://cs.sensiolabs.org/download/php-cs-fixer-v2.phar
      dest: /usr/local/bin/php-cs-fixer
      owner: root
      group: root
      mode: "0755"
