---
- name: Install vim and dependencies
  when: ansible_os_family == "Debian"
  apt:
      name: "{{item}}"
      state: installed
      update_cache: yes
  become: true
  with_items:
      - vim
      - git
      - clang
      - build-essential
      - cmake
      - python-dev
      - exuberant-ctags
      - realpath
      - golang-go

- name: Create directories 
  file:
      path: "{{item}}"
      state: directory
      recurse: true
  with_items:
      - "{{local_repositories_dir}}"
      - "~/.vim/bundle"
      - "~/.vim/autoload"

- name: Install Vim configuration files
  copy:
      dest: "~/.vimrc"
      src: vimrc

- name: Install Vim plugins
  include: install_vim_plugins.yml
