---
- name: Install vim and dependencies, Debian version
  when: ansible_os_family == "Debian"
  apt:
      name: "{{item}}"
      state: installed
      update_cache: yes
  become: true
  with_items:
      - vim
      - git
      - clang
      - build-essential
      - cmake
      - python-dev
      - exuberant-ctags
      - realpath
      - golang-go
      - tmux

- name: Install vim and dependencies, RedHat version
  when: ansible_os_family == "RedHat"
  yum:
      name: "{{item}}"
      state: installed
  become: true
  with_items:
      - vim-enhanced
      - git
      - clang
      - gcc
      - gcc-c++
      - cmake
      - python-devel
      - ctags
      - golang-bin
      - golang-docs
      - tmux

- set_fact: ctags=ctags
  when: ansible_os_family == "RedHat"

- set_fact: ctags=ctags-exuberant
  when: ansible_os_family == "Debian"

- name: Create directories 
  file:
      path: "{{item}}"
      state: directory
      recurse: true
  with_items:
      - "{{local_repositories_dir}}"
      - "{{ansible_user_dir}}/.vim/bundle"
      - "{{ansible_user_dir}}/.vim/autoload"

- name: Have ctags
  command: "{{ctags}} --fields=+S --sort=yes -f {{ansible_user_dir}}/.vim/{{item.outfile}} -R {{item.path}}"
  args:
      creates: "{{ansible_user_dir}}/.vim/{{item.outfile}}"
  with_items:
      - {outfile: "systags", path: "/usr/include"}

- name: Install Vim configuration files
  copy:
      dest: "{{ansible_user_dir}}/.vimrc"
      src: vimrc

- name: Install TMUX configuration file
  copy:
      dest: "{{ansible_user_dir}}/.tmux.conf"
      src: tmux.conf

- name: Install Vim plugins
  include: install_vim_plugins.yml
